# One Hot Encoding and Training with LightGBM 

- In this first attempt I perform One Hot Encoding to the categorical features and ordinal encoding for the 'size' variable. Later I will train a LightGBM regressor with default parameters to predict The Price target variable.

In [4]:
import pandas as pd

In [ ]:
# If using local environment
df = pd.read_csv('cat_backpack.csv')

- One hot encoding for non hierarchycal features.

In [7]:

# Select the categorical columns to be encoded
categorical_cols = ['brand', 'material', 'style', 'color']

# Apply one-hot encoding using get_dummies
encoded_data = pd.get_dummies(df[categorical_cols], prefix=categorical_cols)

# Concatenate the encoded data with the original DataFrame
df = pd.concat([df, encoded_data], axis=1)

# Drop the original categorical columns
df.drop(categorical_cols, axis=1, inplace=True)

- Ordinal encoding for 'size' column.

In [8]:
# Create a dictionary to map size categories to numerical values
size_mapping = {
    'Small': 0,
    'Medium': 1,
    'Large': 2,
    'Unknown': 3  # Or you can assign it -1 or another distinct value
}

# Apply the mapping to the 'size' column
df['size_encoded'] = df['size'].map(size_mapping)

# Drop the original 'size' column (optional)
df.drop('size', axis=1, inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 29 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   id                  300000 non-null  int64  
 1   compartments        300000 non-null  int64  
 2   laptop_compartment  300000 non-null  bool   
 3   waterproof          300000 non-null  bool   
 4   weight_cap          300000 non-null  float64
 5   Price               300000 non-null  float64
 6   brand_Adidas        300000 non-null  bool   
 7   brand_Jansport      300000 non-null  bool   
 8   brand_Nike          300000 non-null  bool   
 9   brand_Puma          300000 non-null  bool   
 10  brand_Under Armour  300000 non-null  bool   
 11  brand_Unknown       300000 non-null  bool   
 12  material_Canvas     300000 non-null  bool   
 13  material_Leather    300000 non-null  bool   
 14  material_Nylon      300000 non-null  bool   
 15  material_Polyester  300000 non-nul

# Train with LigthGBM.

In [10]:
%pip install lightgbm

Note: you may need to restart the kernel to use updated packages.


In [11]:
# Import necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import lightgbm as lgb
from sklearn.metrics import mean_squared_error

# Drop the id column
df = df.drop(columns=['id'])

# Separate features and target variable
X = df.drop(columns=['Price'])
y = df['Price']

# Split into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Instantiate the scaler and fit on training data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create LightGBM datasets
train_data = lgb.Dataset(X_train_scaled, label=y_train)
test_data = lgb.Dataset(X_test_scaled, label=y_test, reference=train_data)

# Set up model parameters
params = {
    'objective': 'regression',
    'metric': 'rmse',
    'verbosity': -1,
    'boosting_type': 'gbdt',
    'seed': 42
}

In [12]:
# Train the model
regressor = lgb.train(
    params,
    train_data,
    num_boost_round=1000,
    valid_sets=[test_data],
    callbacks=[lgb.early_stopping(stopping_rounds=50), lgb.log_evaluation(100)],  # Include log_evaluation callback
    # verbose_eval=100  # Remove this line
)

Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[41]	valid_0's rmse: 38.9136


In [13]:
# Predictions and evaluation
y_pred = regressor.predict(X_test_scaled, num_iteration=regressor.best_iteration)
# Calculate RMSE without the 'squared' argument, then take the square root
mse = mean_squared_error(y_test, y_pred)  # Remove squared=False
rmse = mse**0.5  # Calculate the square root to get RMSE
print("Test RMSE:", rmse)

Test RMSE: 38.91359184477554


In [8]:
# Import necessary libraries
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_error

# Create a new instance of the LGBMRegressor with the best parameters
best_params = {'colsample_bytree': 0.6, 'learning_rate': 0.01, 'max_depth': -1,
              'min_child_samples': 30, 'n_estimators': 100, 'num_leaves': 31,
              'subsample': 0.6}
final_model = LGBMRegressor(**best_params, random_state=42)

# Fit the model to the training data (X_train_scaled, y_train)
final_model.fit(X_train_scaled, y_train)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


LGBMRegressor(colsample_bytree=0.6, learning_rate=0.01, min_child_samples=30,
              random_state=42, subsample=0.6)

In [9]:
# Predict on the test data (X_test_scaled)
y_pred = final_model.predict(X_test_scaled)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


In [10]:
# Calculate the RMSE to evaluate the model's performance
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5
print("Test RMSE with Best Parameters:", rmse)

Test RMSE with Best Parameters: 38.9218926963783


# Optuna with LightGBM

In [11]:
%pip install optuna

Note: you may need to restart the kernel to use updated packages.


In [12]:
import lightgbm as lgb
from sklearn.metrics import mean_squared_error

def objective(trial):
    params = {
        'objective': 'regression',
        'metric': 'rmse',
        'random_state': 42,
        'n_estimators': 100,
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
        'num_leaves': trial.suggest_int('num_leaves', 20, 100),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'min_child_samples': trial.suggest_int('min_child_samples', 20, 200),
        'subsample': trial.suggest_float('subsample', 0.5, 0.9),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 0.9),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0),
    }

    model = lgb.LGBMRegressor(**params)
    # Pass early stopping as a callback
    model.fit(
        X_train_scaled,
        y_train,
        eval_set=[(X_test_scaled, y_test)],
        callbacks=[lgb.early_stopping(stopping_rounds=10)]
    )
    predictions = model.predict(X_test_scaled)
    rmse = mean_squared_error(y_test, predictions)
    return rmse

In [13]:
import optuna
from optuna.samplers import TPESampler

sampler = TPESampler(seed=1) #  Uses the Tree-Structured Parzen Estimator algorithm [4]
study = optuna.create_study(direction='minimize', sampler = sampler)

[I 2025-02-11 16:06:38,880] A new study created in memory with name: no-name-49ccd584-4f8e-4fb1-afae-6b9a4bda91b3


In [14]:
import time
start_time = time.time()
study.optimize(objective, n_trials=100)
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:40,539] Trial 0 finished with value: 1514.220771409521 and parameters: {'learning_rate': 0.047531980423231666, 'num_leaves': 78, 'max_depth': 3, 'min_child_samples': 74, 'subsample': 0.5587023563268452, 'colsample_bytree': 0.5369354379075191, 'reg_alpha': 1.8626021219141067, 'reg_lambda': 3.45560727697487}. Best is trial 0 with value: 1514.220771409521.


Did not meet early stopping. Best iteration is:
[100]	valid_0's rmse: 38.913


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:41,818] Trial 1 finished with value: 1514.273159852056 and parameters: {'learning_rate': 0.0457090726807603, 'num_leaves': 63, 'max_depth': 7, 'min_child_samples': 144, 'subsample': 0.581780899892607, 'colsample_bytree': 0.8512469745563782, 'reg_alpha': 0.27387594170538565, 'reg_lambda': 6.704675105079347}. Best is trial 0 with value: 1514.220771409521.


Early stopping, best iteration is:
[36]	valid_0's rmse: 38.9137


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:43,192] Trial 2 finished with value: 1514.0329287984187 and parameters: {'learning_rate': 0.047557432213041435, 'num_leaves': 65, 'max_depth': 4, 'min_child_samples': 55, 'subsample': 0.8202978274702146, 'colsample_bytree': 0.887304630287759, 'reg_alpha': 3.134241788458186, 'reg_lambda': 6.923226159769914}. Best is trial 2 with value: 1514.0329287984187.


Did not meet early stopping. Best iteration is:
[98]	valid_0's rmse: 38.9106


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:44,352] Trial 3 finished with value: 1514.0833571393748 and parameters: {'learning_rate': 0.08887502370664345, 'num_leaves': 92, 'max_depth': 3, 'min_child_samples': 27, 'subsample': 0.5679321678258276, 'colsample_bytree': 0.8512570013717653, 'reg_alpha': 0.9834683473470326, 'reg_lambda': 4.211076255839445}. Best is trial 2 with value: 1514.0329287984187.


Early stopping, best iteration is:
[74]	valid_0's rmse: 38.9112


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:45,386] Trial 4 finished with value: 1514.4375841272856 and parameters: {'learning_rate': 0.09621005771354518, 'num_leaves': 63, 'max_depth': 9, 'min_child_samples': 77, 'subsample': 0.7746003710726335, 'colsample_bytree': 0.8338502687589492, 'reg_alpha': 0.18288278325903526, 'reg_lambda': 7.501443151948231}. Best is trial 2 with value: 1514.0329287984187.


Early stopping, best iteration is:
[23]	valid_0's rmse: 38.9158


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:47,210] Trial 5 finished with value: 1513.7200049780752 and parameters: {'learning_rate': 0.09899749800158453, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 162, 'subsample': 0.5412904026310568, 'colsample_bytree': 0.679157410470362, 'reg_alpha': 9.085955031845, 'reg_lambda': 2.936141490800653}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[48]	valid_0's rmse: 38.9066


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:49,166] Trial 6 finished with value: 1514.3886128759839 and parameters: {'learning_rate': 0.03589978047277139, 'num_leaves': 30, 'max_depth': 3, 'min_child_samples': 142, 'subsample': 0.5846512464000236, 'colsample_bytree': 0.6062186637488904, 'reg_alpha': 4.915731597887651, 'reg_lambda': 0.5336254606371784}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[100]	valid_0's rmse: 38.9151


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:50,745] Trial 7 finished with value: 1514.121008506416 and parameters: {'learning_rate': 0.061670584494281186, 'num_leaves': 31, 'max_depth': 8, 'min_child_samples': 146, 'subsample': 0.5409337715311303, 'colsample_bytree': 0.6656223951278273, 'reg_alpha': 6.944001580333449, 'reg_lambda': 4.141792701127233}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[53]	valid_0's rmse: 38.9117


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds
Did not meet early stopping. Best iteration is:
[100]	valid_0's rmse: 38.9157


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:53,079] Trial 8 finished with value: 1514.4281480106288 and parameters: {'learning_rate': 0.014495811305147845, 'num_leaves': 63, 'max_depth': 9, 'min_child_samples': 113, 'subsample': 0.8778379023963254, 'colsample_bytree': 0.7346220162007971, 'reg_alpha': 9.034019153844817, 'reg_lambda': 1.374747050087628}. Best is trial 5 with value: 1513.7200049780752.
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:55,587] Trial 9 finished with value: 1514.0909656794004 and parameters: {'learning_rate': 0.02253487125256827, 'num_leaves': 85, 'max_depth': 6, 'min_child_samples': 49, 'subsample': 0.8710034321584136, 'colsample_bytree': 0.6391063438982026, 'reg_alpha': 7.508121033853434, 'reg_lambda': 7.259979856244534}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[100]	valid_0's rmse: 38.9113


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:56,982] Trial 10 finished with value: 1514.4962704798302 and parameters: {'learning_rate': 0.07664503381373533, 'num_leaves': 98, 'max_depth': 12, 'min_child_samples': 198, 'subsample': 0.6845926131589002, 'colsample_bytree': 0.7469170995321801, 'reg_alpha': 9.11826833105835, 'reg_lambda': 9.933903683304415}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[26]	valid_0's rmse: 38.9165


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:06:58,703] Trial 11 finished with value: 1513.9282129133944 and parameters: {'learning_rate': 0.06684945721677582, 'num_leaves': 45, 'max_depth': 5, 'min_child_samples': 190, 'subsample': 0.6978003298225237, 'colsample_bytree': 0.7850967310313143, 'reg_alpha': 3.3038957183056983, 'reg_lambda': 1.9746364046322133}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[80]	valid_0's rmse: 38.9092


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:00,372] Trial 12 finished with value: 1513.8248920284711 and parameters: {'learning_rate': 0.07428649803079343, 'num_leaves': 44, 'max_depth': 5, 'min_child_samples': 187, 'subsample': 0.6561446571865954, 'colsample_bytree': 0.7768821757418434, 'reg_alpha': 4.140769139504529, 'reg_lambda': 2.014622805956238}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[68]	valid_0's rmse: 38.9079


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:01,796] Trial 13 finished with value: 1514.1903511487317 and parameters: {'learning_rate': 0.08001948055823521, 'num_leaves': 45, 'max_depth': 5, 'min_child_samples': 169, 'subsample': 0.6409259637895369, 'colsample_bytree': 0.7094033347930252, 'reg_alpha': 5.158919196273004, 'reg_lambda': 2.526235231286647}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[33]	valid_0's rmse: 38.9126


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:03,157] Trial 14 finished with value: 1513.9577145665626 and parameters: {'learning_rate': 0.09903669586232307, 'num_leaves': 51, 'max_depth': 6, 'min_child_samples': 170, 'subsample': 0.6445449429626403, 'colsample_bytree': 0.7867095070493977, 'reg_alpha': 5.995512475302119, 'reg_lambda': 5.563503872842066}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[41]	valid_0's rmse: 38.9096


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:04,698] Trial 15 finished with value: 1514.0202005365295 and parameters: {'learning_rate': 0.07958966746275416, 'num_leaves': 77, 'max_depth': 5, 'min_child_samples': 121, 'subsample': 0.5011529555296914, 'colsample_bytree': 0.5900606806018389, 'reg_alpha': 3.7173177394475756, 'reg_lambda': 0.3253914201872852}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[48]	valid_0's rmse: 38.9104


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:06,515] Trial 16 finished with value: 1513.961479579 and parameters: {'learning_rate': 0.08798950317602951, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 170, 'subsample': 0.7376802239832089, 'colsample_bytree': 0.5018534021398808, 'reg_alpha': 7.7742962863834535, 'reg_lambda': 2.754666589917196}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[50]	valid_0's rmse: 38.9097


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:07,770] Trial 17 finished with value: 1514.3509991443077 and parameters: {'learning_rate': 0.0695041058537572, 'num_leaves': 51, 'max_depth': 11, 'min_child_samples': 185, 'subsample': 0.6380824217420453, 'colsample_bytree': 0.779951401834214, 'reg_alpha': 9.712531262436126, 'reg_lambda': 5.135902383212916}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[34]	valid_0's rmse: 38.9147


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:09,265] Trial 18 finished with value: 1514.0037995959008 and parameters: {'learning_rate': 0.08731305590021585, 'num_leaves': 74, 'max_depth': 4, 'min_child_samples': 128, 'subsample': 0.503109898279987, 'colsample_bytree': 0.6876757855694724, 'reg_alpha': 4.931021568947625, 'reg_lambda': 1.479563815558016}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[65]	valid_0's rmse: 38.9102


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:10,928] Trial 19 finished with value: 1514.0484826092381 and parameters: {'learning_rate': 0.058785031430348855, 'num_leaves': 39, 'max_depth': 6, 'min_child_samples': 99, 'subsample': 0.7665573468071322, 'colsample_bytree': 0.6408208394362978, 'reg_alpha': 2.12874996686627, 'reg_lambda': 3.6399663288179647}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[49]	valid_0's rmse: 38.9108


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[29]	valid_0's rmse: 38.915


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:13,125] Trial 20 finished with value: 1514.3752086597572 and parameters: {'learning_rate': 0.07117809124381552, 'num_leaves': 71, 'max_depth': 8, 'min_child_samples': 157, 'subsample': 0.6115379998221554, 'colsample_bytree': 0.7482863087894697, 'reg_alpha': 6.231889354168658, 'reg_lambda': 2.7608390301237047}. Best is trial 5 with value: 1513.7200049780752.
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:16,520] Trial 21 finished with value: 1514.1559305829128 and parameters: {'learning_rate': 0.06523856532903002, 'num_leaves': 52, 'max_depth': 5, 'min_child_samples': 200, 'subsample': 0.6985069321407268, 'colsample_bytree': 0.8050901272564122, 'reg_alpha': 3.5389532396320122, 'reg_lambda': 1.4958558856868325}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[77]	valid_0's rmse: 38.9122


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:18,210] Trial 22 finished with value: 1513.9749609764149 and parameters: {'learning_rate': 0.07288156915946212, 'num_leaves': 40, 'max_depth': 4, 'min_child_samples': 184, 'subsample': 0.675173537169364, 'colsample_bytree': 0.7136808429148379, 'reg_alpha': 3.8965065069894624, 'reg_lambda': 2.337155935488784}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[87]	valid_0's rmse: 38.9098


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:20,240] Trial 23 finished with value: 1514.2291576378786 and parameters: {'learning_rate': 0.05458023848195637, 'num_leaves': 56, 'max_depth': 5, 'min_child_samples': 182, 'subsample': 0.742585877846456, 'colsample_bytree': 0.7689115984735766, 'reg_alpha': 2.3619518512290503, 'reg_lambda': 0.01023485021828141}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[69]	valid_0's rmse: 38.9131


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:21,681] Trial 24 finished with value: 1514.2894714580355 and parameters: {'learning_rate': 0.08393091210001612, 'num_leaves': 41, 'max_depth': 6, 'min_child_samples': 200, 'subsample': 0.7183524831731225, 'colsample_bytree': 0.81903029862746, 'reg_alpha': 4.512569545377751, 'reg_lambda': 1.8696210769683197}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[44]	valid_0's rmse: 38.9139


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:23,463] Trial 25 finished with value: 1513.9464932708522 and parameters: {'learning_rate': 0.09350446007316872, 'num_leaves': 30, 'max_depth': 4, 'min_child_samples': 160, 'subsample': 0.8100520567672524, 'colsample_bytree': 0.6840958371099056, 'reg_alpha': 2.7902722988298154, 'reg_lambda': 0.9200643514730487}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[75]	valid_0's rmse: 38.9095


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:25,601] Trial 26 finished with value: 1514.1013944255787 and parameters: {'learning_rate': 0.03386612389573991, 'num_leaves': 84, 'max_depth': 7, 'min_child_samples': 182, 'subsample': 0.6634610610898822, 'colsample_bytree': 0.8731423850657485, 'reg_alpha': 1.4011133908049707, 'reg_lambda': 3.3114315368820373}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[70]	valid_0's rmse: 38.9115


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:27,053] Trial 27 finished with value: 1514.1170931456982 and parameters: {'learning_rate': 0.06428538893730215, 'num_leaves': 46, 'max_depth': 5, 'min_child_samples': 131, 'subsample': 0.6126367106530611, 'colsample_bytree': 0.7263450475499773, 'reg_alpha': 6.157186320118185, 'reg_lambda': 4.383746274809213}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[65]	valid_0's rmse: 38.9117


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:28,845] Trial 28 finished with value: 1513.8655161278036 and parameters: {'learning_rate': 0.05350416994649588, 'num_leaves': 20, 'max_depth': 4, 'min_child_samples': 155, 'subsample': 0.5344844146986468, 'colsample_bytree': 0.764847812882362, 'reg_alpha': 4.296745769404387, 'reg_lambda': 2.0589300878064103}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[100]	valid_0's rmse: 38.9084


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:30,812] Trial 29 finished with value: 1514.2346282807973 and parameters: {'learning_rate': 0.05249864428003231, 'num_leaves': 70, 'max_depth': 3, 'min_child_samples': 97, 'subsample': 0.5355443630072033, 'colsample_bytree': 0.5802194865683233, 'reg_alpha': 8.198340894307698, 'reg_lambda': 3.1656085370033686}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[98]	valid_0's rmse: 38.9132


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:32,992] Trial 30 finished with value: 1514.1072502412565 and parameters: {'learning_rate': 0.03732887168164496, 'num_leaves': 22, 'max_depth': 4, 'min_child_samples': 158, 'subsample': 0.5256223889093542, 'colsample_bytree': 0.6559944837321677, 'reg_alpha': 4.175601601209979, 'reg_lambda': 3.6255533165963105}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[100]	valid_0's rmse: 38.9115


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:34,794] Trial 31 finished with value: 1514.2336254679 and parameters: {'learning_rate': 0.043429911129536536, 'num_leaves': 34, 'max_depth': 3, 'min_child_samples': 176, 'subsample': 0.6008155529283754, 'colsample_bytree': 0.7677626764286013, 'reg_alpha': 5.459270558560901, 'reg_lambda': 2.126108407403352}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[100]	valid_0's rmse: 38.9132


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:36,783] Trial 32 finished with value: 1514.2864251617211 and parameters: {'learning_rate': 0.05663155231025058, 'num_leaves': 56, 'max_depth': 6, 'min_child_samples': 149, 'subsample': 0.5834425153701834, 'colsample_bytree': 0.8012084038560707, 'reg_alpha': 2.9941029697377295, 'reg_lambda': 1.05590978683199}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[47]	valid_0's rmse: 38.9138


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:38,711] Trial 33 finished with value: 1514.0370969389103 and parameters: {'learning_rate': 0.04801057957759909, 'num_leaves': 25, 'max_depth': 4, 'min_child_samples': 191, 'subsample': 0.54229705368353, 'colsample_bytree': 0.7539792229598202, 'reg_alpha': 4.440790165141625, 'reg_lambda': 2.046417790009098}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[99]	valid_0's rmse: 38.9106


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:40,690] Trial 34 finished with value: 1514.0796960568007 and parameters: {'learning_rate': 0.06544754641414015, 'num_leaves': 36, 'max_depth': 5, 'min_child_samples': 137, 'subsample': 0.5521649803536909, 'colsample_bytree': 0.8470158647327151, 'reg_alpha': 1.4883321449378468, 'reg_lambda': 0.9148102277803116}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[60]	valid_0's rmse: 38.9112


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:42,807] Trial 35 finished with value: 1514.1980968387888 and parameters: {'learning_rate': 0.04178162159913109, 'num_leaves': 84, 'max_depth': 7, 'min_child_samples': 159, 'subsample': 0.5738710565441766, 'colsample_bytree': 0.8213710741038461, 'reg_alpha': 3.221497283971058, 'reg_lambda': 2.863639661217884}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[43]	valid_0's rmse: 38.9127


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:44,452] Trial 36 finished with value: 1514.2286157680583 and parameters: {'learning_rate': 0.05111758803734478, 'num_leaves': 27, 'max_depth': 3, 'min_child_samples': 167, 'subsample': 0.7136102195912459, 'colsample_bytree': 0.8760167770115708, 'reg_alpha': 5.573547446568296, 'reg_lambda': 4.669713616391281}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[92]	valid_0's rmse: 38.9131


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:45,692] Trial 37 finished with value: 1514.1853912244371 and parameters: {'learning_rate': 0.09394436852353497, 'num_leaves': 58, 'max_depth': 5, 'min_child_samples': 193, 'subsample': 0.8206423698500896, 'colsample_bytree': 0.7948014768458238, 'reg_alpha': 6.72318692404478, 'reg_lambda': 3.7991245385779306}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[36]	valid_0's rmse: 38.9125


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:47,283] Trial 38 finished with value: 1514.2553337628574 and parameters: {'learning_rate': 0.07400045459239221, 'num_leaves': 45, 'max_depth': 9, 'min_child_samples': 147, 'subsample': 0.627771839522434, 'colsample_bytree': 0.7014480229257859, 'reg_alpha': 2.536193892112969, 'reg_lambda': 5.960461334368179}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[47]	valid_0's rmse: 38.9134


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:48,959] Trial 39 finished with value: 1514.0966197362945 and parameters: {'learning_rate': 0.060988775773861525, 'num_leaves': 67, 'max_depth': 3, 'min_child_samples': 178, 'subsample': 0.6578285996531986, 'colsample_bytree': 0.7274638022030413, 'reg_alpha': 0.6303071442527086, 'reg_lambda': 8.557919529708563}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[90]	valid_0's rmse: 38.9114


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:50,651] Trial 40 finished with value: 1513.975895610022 and parameters: {'learning_rate': 0.08295628823160041, 'num_leaves': 100, 'max_depth': 4, 'min_child_samples': 61, 'subsample': 0.5204276779397167, 'colsample_bytree': 0.6746513951777244, 'reg_alpha': 3.384086427169724, 'reg_lambda': 1.8125582997542085}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[75]	valid_0's rmse: 38.9098


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:52,664] Trial 41 finished with value: 1513.9145435699086 and parameters: {'learning_rate': 0.09427644756658075, 'num_leaves': 20, 'max_depth': 4, 'min_child_samples': 160, 'subsample': 0.8128517938961629, 'colsample_bytree': 0.6248441461837781, 'reg_alpha': 2.7620057956135766, 'reg_lambda': 0.9184470781891563}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[71]	valid_0's rmse: 38.9091


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:54,046] Trial 42 finished with value: 1514.0255240972979 and parameters: {'learning_rate': 0.09838777416508085, 'num_leaves': 27, 'max_depth': 4, 'min_child_samples': 151, 'subsample': 0.8376305730980619, 'colsample_bytree': 0.6163049087712272, 'reg_alpha': 4.133372843270334, 'reg_lambda': 0.5588906845720207}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[48]	valid_0's rmse: 38.9105


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:55,798] Trial 43 finished with value: 1513.9539050482188 and parameters: {'learning_rate': 0.09224261243128831, 'num_leaves': 21, 'max_depth': 6, 'min_child_samples': 189, 'subsample': 0.7564736428537004, 'colsample_bytree': 0.6327077166950225, 'reg_alpha': 1.9605448300352708, 'reg_lambda': 1.2616532866133348}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[71]	valid_0's rmse: 38.9096


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:57,702] Trial 44 finished with value: 1514.0887300197733 and parameters: {'learning_rate': 0.09040673655566071, 'num_leaves': 92, 'max_depth': 5, 'min_child_samples': 27, 'subsample': 0.5627164682007404, 'colsample_bytree': 0.6068435771442243, 'reg_alpha': 2.9070126206489726, 'reg_lambda': 2.3636714732768196}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[42]	valid_0's rmse: 38.9113


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:07:59,318] Trial 45 finished with value: 1514.0508179867172 and parameters: {'learning_rate': 0.09965696311481222, 'num_leaves': 34, 'max_depth': 4, 'min_child_samples': 167, 'subsample': 0.8994536529534674, 'colsample_bytree': 0.5759250882407232, 'reg_alpha': 4.729022636170229, 'reg_lambda': 1.682472297764152}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[40]	valid_0's rmse: 38.9108


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:00,754] Trial 46 finished with value: 1514.0232262648713 and parameters: {'learning_rate': 0.07715714777068895, 'num_leaves': 62, 'max_depth': 3, 'min_child_samples': 175, 'subsample': 0.800493469676454, 'colsample_bytree': 0.8318055739705384, 'reg_alpha': 3.758104398768646, 'reg_lambda': 3.0834315421641723}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[98]	valid_0's rmse: 38.9105


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:02,241] Trial 47 finished with value: 1514.044154430869 and parameters: {'learning_rate': 0.08635547151799775, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 134, 'subsample': 0.7834092635717271, 'colsample_bytree': 0.6569830394249155, 'reg_alpha': 1.7178300373938584, 'reg_lambda': 0.5891343608976087}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[51]	valid_0's rmse: 38.9107


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds
Did not meet early stopping. Best iteration is:
[100]	valid_0's rmse: 38.9142


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:05,033] Trial 48 finished with value: 1514.3118544159884 and parameters: {'learning_rate': 0.02794047909925413, 'num_leaves': 48, 'max_depth': 10, 'min_child_samples': 110, 'subsample': 0.6837855385057698, 'colsample_bytree': 0.5478826588138324, 'reg_alpha': 5.139289791128864, 'reg_lambda': 2.477987187617445}. Best is trial 5 with value: 1513.7200049780752.
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:06,286] Trial 49 finished with value: 1514.3510415840485 and parameters: {'learning_rate': 0.06711140334147805, 'num_leaves': 31, 'max_depth': 6, 'min_child_samples': 123, 'subsample': 0.7065411239071138, 'colsample_bytree': 0.7714724149194461, 'reg_alpha': 9.93809775409183, 'reg_lambda': 0.0592396991975942}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[34]	valid_0's rmse: 38.9147


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:07,603] Trial 50 finished with value: 1514.0941609655608 and parameters: {'learning_rate': 0.08083360759285663, 'num_leaves': 25, 'max_depth': 7, 'min_child_samples': 141, 'subsample': 0.5977396571171492, 'colsample_bytree': 0.8993998189420546, 'reg_alpha': 8.726803477939638, 'reg_lambda': 0.7037410067563692}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[52]	valid_0's rmse: 38.9114


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:09,189] Trial 51 finished with value: 1513.842689573582 and parameters: {'learning_rate': 0.09586619342293616, 'num_leaves': 20, 'max_depth': 4, 'min_child_samples': 164, 'subsample': 0.8449477078320734, 'colsample_bytree': 0.6786661609548086, 'reg_alpha': 2.316432898826984, 'reg_lambda': 1.1157003304387785}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[64]	valid_0's rmse: 38.9081


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:10,547] Trial 52 finished with value: 1514.0132708322221 and parameters: {'learning_rate': 0.0957866160035863, 'num_leaves': 21, 'max_depth': 4, 'min_child_samples': 164, 'subsample': 0.8499794014490221, 'colsample_bytree': 0.6860645221811552, 'reg_alpha': 2.3784951588954186, 'reg_lambda': 1.2773130273202116}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[58]	valid_0's rmse: 38.9103


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:11,976] Trial 53 finished with value: 1514.234404030913 and parameters: {'learning_rate': 0.09013071768900119, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 153, 'subsample': 0.8798572495964279, 'colsample_bytree': 0.7459565447626487, 'reg_alpha': 3.4040529816049654, 'reg_lambda': 1.6113723597428697}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[39]	valid_0's rmse: 38.9132


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:13,676] Trial 54 finished with value: 1514.0404131015841 and parameters: {'learning_rate': 0.09635081692029643, 'num_leaves': 26, 'max_depth': 4, 'min_child_samples': 175, 'subsample': 0.7351166463781741, 'colsample_bytree': 0.7174977764673488, 'reg_alpha': 4.141105192013755, 'reg_lambda': 1.978390965828607}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[71]	valid_0's rmse: 38.9107


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:15,763] Trial 55 finished with value: 1514.1119313163438 and parameters: {'learning_rate': 0.06909728421124028, 'num_leaves': 29, 'max_depth': 3, 'min_child_samples': 191, 'subsample': 0.8564001459545293, 'colsample_bytree': 0.6462613457379816, 'reg_alpha': 2.7666082274324006, 'reg_lambda': 2.650342899281723}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[96]	valid_0's rmse: 38.9116


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:17,655] Trial 56 finished with value: 1514.0543024430647 and parameters: {'learning_rate': 0.08475058217751591, 'num_leaves': 42, 'max_depth': 5, 'min_child_samples': 172, 'subsample': 0.7906180686987324, 'colsample_bytree': 0.6975551649291754, 'reg_alpha': 3.8004557930990908, 'reg_lambda': 1.0839358687605172}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[39]	valid_0's rmse: 38.9109


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:19,357] Trial 57 finished with value: 1514.2066397556553 and parameters: {'learning_rate': 0.07637826148835937, 'num_leaves': 93, 'max_depth': 4, 'min_child_samples': 143, 'subsample': 0.7595890919007661, 'colsample_bytree': 0.6242596121097118, 'reg_alpha': 0.7325632461856066, 'reg_lambda': 0.32788413859180476}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[39]	valid_0's rmse: 38.9128


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:20,623] Trial 58 finished with value: 1514.3027905732188 and parameters: {'learning_rate': 0.061410337082797875, 'num_leaves': 36, 'max_depth': 6, 'min_child_samples': 162, 'subsample': 0.6573518984449572, 'colsample_bytree': 0.7383907933247997, 'reg_alpha': 1.0936487712004126, 'reg_lambda': 2.2029210805310186}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[34]	valid_0's rmse: 38.914


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:22,534] Trial 59 finished with value: 1514.1700499788565 and parameters: {'learning_rate': 0.08845974397308182, 'num_leaves': 24, 'max_depth': 12, 'min_child_samples': 183, 'subsample': 0.5102000688734404, 'colsample_bytree': 0.6712859890645394, 'reg_alpha': 5.582994594503286, 'reg_lambda': 3.8731240121177706}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[59]	valid_0's rmse: 38.9123


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:24,248] Trial 60 finished with value: 1514.091955417289 and parameters: {'learning_rate': 0.058500346893437936, 'num_leaves': 53, 'max_depth': 5, 'min_child_samples': 197, 'subsample': 0.8207097846171324, 'colsample_bytree': 0.7649454215985168, 'reg_alpha': 0.053683573192080836, 'reg_lambda': 3.018784828657761}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[66]	valid_0's rmse: 38.9113


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:25,613] Trial 61 finished with value: 1514.1376550369819 and parameters: {'learning_rate': 0.09404314989354624, 'num_leaves': 29, 'max_depth': 4, 'min_child_samples': 158, 'subsample': 0.8065737773894155, 'colsample_bytree': 0.6896967527919444, 'reg_alpha': 2.651542494252249, 'reg_lambda': 1.458656386959299}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[52]	valid_0's rmse: 38.9119


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:27,213] Trial 62 finished with value: 1513.9774608865544 and parameters: {'learning_rate': 0.09988194812602996, 'num_leaves': 33, 'max_depth': 3, 'min_child_samples': 164, 'subsample': 0.837297832029373, 'colsample_bytree': 0.7833475735360855, 'reg_alpha': 2.142386808533399, 'reg_lambda': 0.8075383769998918}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[73]	valid_0's rmse: 38.9099


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:29,134] Trial 63 finished with value: 1513.9617510870698 and parameters: {'learning_rate': 0.09351402540219485, 'num_leaves': 23, 'max_depth': 4, 'min_child_samples': 154, 'subsample': 0.8673785558111383, 'colsample_bytree': 0.6752452473544535, 'reg_alpha': 3.2596127924813425, 'reg_lambda': 1.1536655772497137}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[65]	valid_0's rmse: 38.9097


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:31,536] Trial 64 finished with value: 1513.8922217629568 and parameters: {'learning_rate': 0.09167880972955945, 'num_leaves': 37, 'max_depth': 5, 'min_child_samples': 179, 'subsample': 0.833274830032072, 'colsample_bytree': 0.7087471106126698, 'reg_alpha': 4.590444267701789, 'reg_lambda': 0.24937487824059357}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[53]	valid_0's rmse: 38.9088


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:33,250] Trial 65 finished with value: 1514.232731987926 and parameters: {'learning_rate': 0.09652281816685289, 'num_leaves': 38, 'max_depth': 6, 'min_child_samples': 179, 'subsample': 0.6916544359268687, 'colsample_bytree': 0.7059286504502142, 'reg_alpha': 4.230866267873083, 'reg_lambda': 0.2937997885169892}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[33]	valid_0's rmse: 38.9131


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:34,955] Trial 66 finished with value: 1514.0610094118801 and parameters: {'learning_rate': 0.08572233363232218, 'num_leaves': 49, 'max_depth': 5, 'min_child_samples': 188, 'subsample': 0.8363729529412826, 'colsample_bytree': 0.8108729149072159, 'reg_alpha': 4.58235647673526, 'reg_lambda': 1.7198000627334706}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[41]	valid_0's rmse: 38.9109


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:36,525] Trial 67 finished with value: 1514.076874620625 and parameters: {'learning_rate': 0.08132235914083644, 'num_leaves': 44, 'max_depth': 5, 'min_child_samples': 172, 'subsample': 0.8893381307772391, 'colsample_bytree': 0.652033505000393, 'reg_alpha': 4.987278171080613, 'reg_lambda': 2.0689299688346265}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[33]	valid_0's rmse: 38.9111


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:38,343] Trial 68 finished with value: 1514.2146622005912 and parameters: {'learning_rate': 0.08942626696577352, 'num_leaves': 37, 'max_depth': 5, 'min_child_samples': 195, 'subsample': 0.7212414860815884, 'colsample_bytree': 0.7572699304052724, 'reg_alpha': 7.144012950638837, 'reg_lambda': 0.3060946450545562}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[44]	valid_0's rmse: 38.9129


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:39,986] Trial 69 finished with value: 1514.237151183147 and parameters: {'learning_rate': 0.0474913477374131, 'num_leaves': 43, 'max_depth': 6, 'min_child_samples': 82, 'subsample': 0.5547439184909461, 'colsample_bytree': 0.7223298949744643, 'reg_alpha': 3.0798454245828992, 'reg_lambda': 1.4015489847255531}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[39]	valid_0's rmse: 38.9132


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:41,405] Trial 70 finished with value: 1514.460269509051 and parameters: {'learning_rate': 0.0781355416711463, 'num_leaves': 32, 'max_depth': 8, 'min_child_samples': 184, 'subsample': 0.7726595113450696, 'colsample_bytree': 0.7929484515352496, 'reg_alpha': 5.911945777383824, 'reg_lambda': 3.443965497724796}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[39]	valid_0's rmse: 38.9161


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:43,092] Trial 71 finished with value: 1513.929311284119 and parameters: {'learning_rate': 0.09224958874226738, 'num_leaves': 28, 'max_depth': 4, 'min_child_samples': 168, 'subsample': 0.8158480612938935, 'colsample_bytree': 0.7342282718646576, 'reg_alpha': 3.6522648357471397, 'reg_lambda': 0.8808293133817906}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[73]	valid_0's rmse: 38.9092


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:46,773] Trial 72 finished with value: 1514.0793406078185 and parameters: {'learning_rate': 0.09175934960557196, 'num_leaves': 28, 'max_depth': 4, 'min_child_samples': 168, 'subsample': 0.8608135905851109, 'colsample_bytree': 0.7348896165767084, 'reg_alpha': 3.578781593825735, 'reg_lambda': 0.9282967946719312}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[58]	valid_0's rmse: 38.9112


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:49,081] Trial 73 finished with value: 1514.2171168092443 and parameters: {'learning_rate': 0.09648053367002091, 'num_leaves': 23, 'max_depth': 4, 'min_child_samples': 187, 'subsample': 0.6692406571534055, 'colsample_bytree': 0.7785544397496509, 'reg_alpha': 4.797916828925478, 'reg_lambda': 0.004271486372435573}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[40]	valid_0's rmse: 38.9129


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:50,793] Trial 74 finished with value: 1514.010227342758 and parameters: {'learning_rate': 0.05238971122739163, 'num_leaves': 20, 'max_depth': 4, 'min_child_samples': 37, 'subsample': 0.8262696852385787, 'colsample_bytree': 0.74284586130709, 'reg_alpha': 4.24699905774808, 'reg_lambda': 0.6273804229524815}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[99]	valid_0's rmse: 38.9103


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:52,532] Trial 75 finished with value: 1514.2045901608037 and parameters: {'learning_rate': 0.07427877131534089, 'num_leaves': 39, 'max_depth': 5, 'min_child_samples': 178, 'subsample': 0.7987480308314832, 'colsample_bytree': 0.7121498523624773, 'reg_alpha': 3.9119884916483625, 'reg_lambda': 2.389171606323247}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[41]	valid_0's rmse: 38.9128


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:54,190] Trial 76 finished with value: 1514.0289392177538 and parameters: {'learning_rate': 0.0830514824787937, 'num_leaves': 88, 'max_depth': 3, 'min_child_samples': 171, 'subsample': 0.8425489748143415, 'colsample_bytree': 0.756294020765038, 'reg_alpha': 2.270312889959272, 'reg_lambda': 8.157528336663395}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[96]	valid_0's rmse: 38.9105


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:56,125] Trial 77 finished with value: 1513.8313420569373 and parameters: {'learning_rate': 0.08784686133783598, 'num_leaves': 25, 'max_depth': 5, 'min_child_samples': 164, 'subsample': 0.5748828941243752, 'colsample_bytree': 0.6650297837853874, 'reg_alpha': 5.260661396401321, 'reg_lambda': 1.7889769004251277}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[64]	valid_0's rmse: 38.908


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[70]	valid_0's rmse: 38.9099


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:08:58,731] Trial 78 finished with value: 1513.97741513674 and parameters: {'learning_rate': 0.08818711110454343, 'num_leaves': 23, 'max_depth': 6, 'min_child_samples': 154, 'subsample': 0.5371204134833228, 'colsample_bytree': 0.6656379662759081, 'reg_alpha': 8.24440662544027, 'reg_lambda': 1.7611336968587592}. Best is trial 5 with value: 1513.7200049780752.
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:01,093] Trial 79 finished with value: 1513.9859185916307 and parameters: {'learning_rate': 0.07091274117413886, 'num_leaves': 47, 'max_depth': 5, 'min_child_samples': 148, 'subsample': 0.5783031409987259, 'colsample_bytree': 0.6000565137496693, 'reg_alpha': 5.40465682679983, 'reg_lambda': 2.723438113596596}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[66]	valid_0's rmse: 38.91


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[84]	valid_0's rmse: 38.9083


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:03,659] Trial 80 finished with value: 1513.8555767760274 and parameters: {'learning_rate': 0.08561853052693874, 'num_leaves': 25, 'max_depth': 5, 'min_child_samples': 137, 'subsample': 0.6258696576279446, 'colsample_bytree': 0.621480087039135, 'reg_alpha': 1.7483450627774002, 'reg_lambda': 1.9189058103669068}. Best is trial 5 with value: 1513.7200049780752.
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:05,263] Trial 81 finished with value: 1514.0227121005169 and parameters: {'learning_rate': 0.08673354523897679, 'num_leaves': 25, 'max_depth': 5, 'min_child_samples': 141, 'subsample': 0.5980375017223549, 'colsample_bytree': 0.6375333321698793, 'reg_alpha': 1.4472245426407997, 'reg_lambda': 2.2228820620245626}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[47]	valid_0's rmse: 38.9104


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:07,318] Trial 82 finished with value: 1513.9865204281616 and parameters: {'learning_rate': 0.09437346738700425, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 160, 'subsample': 0.6275628089370163, 'colsample_bytree': 0.6260629588980173, 'reg_alpha': 1.7093390465272176, 'reg_lambda': 1.909907086143211}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[51]	valid_0's rmse: 38.91


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:09,304] Trial 83 finished with value: 1513.966188682865 and parameters: {'learning_rate': 0.09145956614681612, 'num_leaves': 54, 'max_depth': 5, 'min_child_samples': 180, 'subsample': 0.6497194609092458, 'colsample_bytree': 0.5703934722193942, 'reg_alpha': 9.364143908654846, 'reg_lambda': 1.3565724006360171}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[50]	valid_0's rmse: 38.9097


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:11,168] Trial 84 finished with value: 1513.9670372822534 and parameters: {'learning_rate': 0.09743067465488169, 'num_leaves': 50, 'max_depth': 4, 'min_child_samples': 127, 'subsample': 0.5259653103329226, 'colsample_bytree': 0.6186636286600439, 'reg_alpha': 6.496581401456211, 'reg_lambda': 9.948071520789895}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[66]	valid_0's rmse: 38.9097


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:13,182] Trial 85 finished with value: 1514.119693662679 and parameters: {'learning_rate': 0.07997276402741474, 'num_leaves': 31, 'max_depth': 5, 'min_child_samples': 156, 'subsample': 0.5663544067973704, 'colsample_bytree': 0.5923785599315349, 'reg_alpha': 1.9392405676487305, 'reg_lambda': 2.51825242333189}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[42]	valid_0's rmse: 38.9117


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:14,881] Trial 86 finished with value: 1514.1945153369122 and parameters: {'learning_rate': 0.08355934800581642, 'num_leaves': 26, 'max_depth': 6, 'min_child_samples': 136, 'subsample': 0.632539711839538, 'colsample_bytree': 0.6625627993307601, 'reg_alpha': 2.507723401843077, 'reg_lambda': 6.313262057749662}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[38]	valid_0's rmse: 38.9127


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:17,338] Trial 87 finished with value: 1514.1030686509998 and parameters: {'learning_rate': 0.05500659618582451, 'num_leaves': 35, 'max_depth': 4, 'min_child_samples': 100, 'subsample': 0.6078445508656977, 'colsample_bytree': 0.6908279641712768, 'reg_alpha': 1.060963630820779, 'reg_lambda': 1.6088862970866593}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[84]	valid_0's rmse: 38.9115


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:19,299] Trial 88 finished with value: 1514.0510421824897 and parameters: {'learning_rate': 0.08891844742079315, 'num_leaves': 22, 'max_depth': 5, 'min_child_samples': 163, 'subsample': 0.5867492661621483, 'colsample_bytree': 0.6405956385194376, 'reg_alpha': 2.9185453601277427, 'reg_lambda': 2.9097637656211393}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[47]	valid_0's rmse: 38.9108


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:21,354] Trial 89 finished with value: 1513.9139850799952 and parameters: {'learning_rate': 0.09818473884820537, 'num_leaves': 75, 'max_depth': 4, 'min_child_samples': 145, 'subsample': 0.5501179024381404, 'colsample_bytree': 0.6794805456326622, 'reg_alpha': 4.466893443720915, 'reg_lambda': 1.1862917124903343}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[60]	valid_0's rmse: 38.909


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:23,643] Trial 90 finished with value: 1514.1386690126544 and parameters: {'learning_rate': 0.0990856037095569, 'num_leaves': 81, 'max_depth': 3, 'min_child_samples': 144, 'subsample': 0.5140950617464366, 'colsample_bytree': 0.6495403783064971, 'reg_alpha': 5.1980606594752645, 'reg_lambda': 1.1550067929955832}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[100]	valid_0's rmse: 38.9119


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:25,662] Trial 91 finished with value: 1513.989787936373 and parameters: {'learning_rate': 0.09398772252820438, 'num_leaves': 74, 'max_depth': 4, 'min_child_samples': 115, 'subsample': 0.5452760761248773, 'colsample_bytree': 0.6790273310076581, 'reg_alpha': 4.356920668443998, 'reg_lambda': 5.067098498637138}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[70]	valid_0's rmse: 38.91


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:27,336] Trial 92 finished with value: 1514.0817883527143 and parameters: {'learning_rate': 0.09510591977435884, 'num_leaves': 74, 'max_depth': 5, 'min_child_samples': 150, 'subsample': 0.619170255819376, 'colsample_bytree': 0.6110599128304958, 'reg_alpha': 4.021548831828858, 'reg_lambda': 1.9538648821583406}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[50]	valid_0's rmse: 38.9112


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:29,084] Trial 93 finished with value: 1513.8110752050543 and parameters: {'learning_rate': 0.09833762241172875, 'num_leaves': 86, 'max_depth': 4, 'min_child_samples': 174, 'subsample': 0.5302225593011872, 'colsample_bytree': 0.6650036814370689, 'reg_alpha': 4.456500054496238, 'reg_lambda': 1.505159404906599}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[84]	valid_0's rmse: 38.9077


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:30,968] Trial 94 finished with value: 1514.1686949345633 and parameters: {'learning_rate': 0.09808874802095423, 'num_leaves': 88, 'max_depth': 3, 'min_child_samples': 164, 'subsample': 0.5323620050459262, 'colsample_bytree': 0.662310164884027, 'reg_alpha': 5.270709498553692, 'reg_lambda': 0.42577974297167304}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[63]	valid_0's rmse: 38.9123


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:32,626] Trial 95 finished with value: 1513.9765933665115 and parameters: {'learning_rate': 0.09716071578803802, 'num_leaves': 78, 'max_depth': 4, 'min_child_samples': 174, 'subsample': 0.5538701261181335, 'colsample_bytree': 0.6940277703126139, 'reg_alpha': 4.616281693299985, 'reg_lambda': 1.3911843361689544}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[61]	valid_0's rmse: 38.9099


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:34,833] Trial 96 finished with value: 1513.9657059794347 and parameters: {'learning_rate': 0.09105415099274453, 'num_leaves': 81, 'max_depth': 3, 'min_child_samples': 152, 'subsample': 0.502018084300806, 'colsample_bytree': 0.6278119845804209, 'reg_alpha': 5.826884151691247, 'reg_lambda': 1.0201544816740342}. Best is trial 5 with value: 1513.7200049780752.


Did not meet early stopping. Best iteration is:
[97]	valid_0's rmse: 38.9097


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:37,029] Trial 97 finished with value: 1514.028632048023 and parameters: {'learning_rate': 0.09519510448431891, 'num_leaves': 90, 'max_depth': 4, 'min_child_samples': 147, 'subsample': 0.5696223960027882, 'colsample_bytree': 0.6691466962490455, 'reg_alpha': 4.819024117216672, 'reg_lambda': 0.6864303909798918}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[60]	valid_0's rmse: 38.9105


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:39,078] Trial 98 finished with value: 1513.8320198242243 and parameters: {'learning_rate': 0.09259057573780116, 'num_leaves': 66, 'max_depth': 4, 'min_child_samples': 138, 'subsample': 0.589748605292708, 'colsample_bytree': 0.707832577095654, 'reg_alpha': 4.533728351959096, 'reg_lambda': 1.5317136102323206}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[72]	valid_0's rmse: 38.908


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
[I 2025-02-11 16:09:41,195] Trial 99 finished with value: 1514.3705318275065 and parameters: {'learning_rate': 0.08742309776645198, 'num_leaves': 69, 'max_depth': 10, 'min_child_samples': 138, 'subsample': 0.5610321539815638, 'colsample_bytree': 0.6836411403664809, 'reg_alpha': 4.406211014889559, 'reg_lambda': 5.434008713487626}. Best is trial 5 with value: 1513.7200049780752.


Early stopping, best iteration is:
[22]	valid_0's rmse: 38.9149
Time taken: 182.3079128265381 seconds


In [15]:
print('Best parameters:', study.best_params)

Best parameters: {'learning_rate': 0.09899749800158453, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 162, 'subsample': 0.5412904026310568, 'colsample_bytree': 0.679157410470362, 'reg_alpha': 9.085955031845, 'reg_lambda': 2.936141490800653}


- first iteration:
Best parameters: {'learning_rate': 0.09495644380018639, 'num_leaves': 77, 'max_depth': 3, 'min_child_samples': 62, 'subsample': 0.6614807453665343, 'colsample_bytree': 0.6148551220728337, 'reg_alpha': 8.500355486635911, 'reg_lambda': 7.010097067336246}
- 2nd iteration:
Best parameters: {'learning_rate': 0.09654269565258655, 'num_leaves': 82, 'max_depth': 3, 'min_child_samples': 77, 'subsample': 0.8443805713604343, 'colsample_bytree': 0.5006284268817309, 'reg_alpha': 4.506548701012825, 'reg_lambda': 3.5879714165911607}
- 3rd
Best Parameters: {'learning_rate': 0.09899749800158453, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 162, 'subsample': 0.5412904026310568, 'colsample_bytree': 0.679157410470362, 'reg_alpha': 9.085955031845, 'reg_lambda': 2.936141490800653}
- 4th iteration:
Best Parameters: {'learning_rate': 0.09689056850918965, 'num_leaves': 45, 'max_depth': 4, 'min_child_samples': 42, 'subsample': 0.7495256437518634, 'colsample_bytree': 0.528430956341894, 'reg_alpha': 9.438202535340269, 'reg_lambda': 5.180036018469718}


In [16]:
import lightgbm as lgb
from sklearn.metrics import mean_squared_error

# Best parameters from Optuna
best_params = study.best_params
print("Best Parameters:", best_params)

# Create and train the model with the best parameters
model = lgb.LGBMRegressor(**best_params)
model.fit(X_train_scaled, y_train, eval_set=[(X_test_scaled, y_test)],
          callbacks=[lgb.early_stopping(stopping_rounds=10)])

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5
print("Test RMSE with Best Parameters:", rmse)

Best Parameters: {'learning_rate': 0.09899749800158453, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 162, 'subsample': 0.5412904026310568, 'colsample_bytree': 0.679157410470362, 'reg_alpha': 9.085955031845, 'reg_lambda': 2.936141490800653}


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[34]	valid_0's l2: 1514.16
Test RMSE with Best Parameters: 38.912187498337296


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
